@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

echo ============================================================
echo  OVERRIDE DEMOTION  (auto-generated 2026-07-19 13:42 UTC)
echo  -----------------------------------------------------------
echo  The out-of-sample OVERRIDE backtest hit the locked demote
echo  threshold:
echo
echo    out-of-sample n: 10
echo    precision:       50.0%%   (threshold: 85%%)
echo    wins flipped:    5  (limit: 2)
echo    verdict reason:  reverse-direction sanity (Rule 11): 5 historical wins flipped >= limit 2; demote OVERRIDE to stake-size cap regardless of precision (50.0%)
echo
echo  Per the locked policy (memory/project_override_backtest_thresholds.md),
echo  OVERRIDE demotes from a direction-flip rule to a stake-size cap:
echo  the 4-condition convergence still kills the bet, but it no
echo  longer claims to know the correct side.
echo
echo  This .bat was auto-generated by tools/backtest_override.py.
echo  Review the change before double-clicking; the harness will
echo  NEVER push automatically.  See override_status.json for the
echo  full per-fire ledger backing this decision.
echo ============================================================
echo.
echo (Patch logic not yet wired — implement when first 'demote' fires)
echo Aborting; nothing pushed.
pause
