"""
score_blend_2026.py
-------------------
Score the 2026 OOS slate with BOTH the v8 lineup-aware model
(models/latest.pkl) and the v7-equivalent (models/v7_equiv.pkl),
then evaluate a range of blend weights.

This validates that the blend Brier lift seen on the preserved
backtest_fill_2026_preds*.csv files reproduces when we actually run
both models through predict() on the same feature frame (vs. the
walk-forward preds that were generated by different training splits).

The goal: pick a final alpha, record the Brier, and confirm the lift
survives. If it does, we wire blending into the predict path and ship.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

from mlb_edge import build_pipeline as bp
from mlb_edge import model as md


def brier(p, y):
    return float(((np.asarray(p) - np.asarray(y)) ** 2).mean())


def acc(p, y):
    return float(((np.asarray(p) >= 0.5).astype(int) == np.asarray(y)).mean())


def main():
    # -----------------------------------------------------------------
    # 1. Build the 2026 frame. Pass `through=2026-04-22` to match the
    #    already-built v5 cache (features_2026_2026-04-22_1_v5.parquet)
    #    instead of triggering a full-season rebuild that re-fetches
    #    Statcast and burns ~30+ min.
    # -----------------------------------------------------------------
    through = date(2026, 4, 22)
    print(f"Building 2026 historical frame through {through} (using v5 cache)...")
    df = bp.build_historical_frame(2026, through=through)
    df = df.dropna(subset=["home_win"]).copy()
    print(f"  {len(df)} games with a final score")

    # -----------------------------------------------------------------
    # 2. Score with v8 (lineup-aware).
    # -----------------------------------------------------------------
    print("\nScoring with v8 (models/latest.pkl)...")
    s1_v8, s2_v8 = md.load("models/latest.pkl")
    preds_v8 = md.predict(s1_v8, s2_v8, df)
    df["p_v8"] = preds_v8["model_prob"].to_numpy()

    # -----------------------------------------------------------------
    # 3. Score with v7-equiv (no lineup features). We need to patch
    #    FULL_FEATURES_EXTRA so `predict()` looks up the right cols.
    # -----------------------------------------------------------------
    print("\nScoring with v7-equiv (models/v7_equiv.pkl)...")
    s1_v7, s2_v7 = md.load("models/v7_equiv.pkl")
    # The TrainedModel carries its own feature_cols, so predict() uses
    # the stored list directly — no monkey-patch needed.
    preds_v7 = md.predict(s1_v7, s2_v7, df)
    df["p_v7"] = preds_v7["model_prob"].to_numpy()

    # -----------------------------------------------------------------
    # 4. Blend sweep
    # -----------------------------------------------------------------
    y = df["home_win"].to_numpy(dtype=int)
    print("\n" + "=" * 78)
    print(f"BLEND SWEEP — 2026 OOS (n={len(df)})")
    print("=" * 78)
    print(f"  {'alpha':>6}  {'Brier':>7}  {'Acc':>7}")
    best_alpha = 0.0
    best_brier = float("inf")
    for alpha in np.linspace(0.0, 1.0, 11):
        pb = alpha * df["p_v7"] + (1 - alpha) * df["p_v8"]
        b = brier(pb, y)
        a = acc(pb, y)
        flag = ""
        if b < best_brier:
            best_brier = b
            best_alpha = alpha
            flag = "  <-- best"
        print(f"  {alpha:6.2f}  {b:.4f}  {a*100:5.2f}%{flag}")

    print(f"\nBest alpha (2026 OOS): {best_alpha:.2f} -> Brier {best_brier:.4f}")
    print("(Sanity check: best alpha on preserved CSVs was also 0.5-0.6)")

    # -----------------------------------------------------------------
    # 5. Write the blended predictions for downstream use.
    # -----------------------------------------------------------------
    df["p_blend_alpha05"] = 0.5 * df["p_v7"] + 0.5 * df["p_v8"]
    df["p_blend_alpha06"] = 0.6 * df["p_v7"] + 0.4 * df["p_v8"]
    out_cols = ["game_id", "game_date", "home_team", "away_team", "home_win",
                "p_v7", "p_v8", "p_blend_alpha05", "p_blend_alpha06"]
    out_df = df[[c for c in out_cols if c in df.columns]].copy()
    out_path = Path("blend_2026_preds.csv")
    out_df.to_csv(out_path, index=False)
    print(f"\nWrote {len(out_df)} rows to {out_path}")


if __name__ == "__main__":
    main()
