"""
tools/run_claude_weekly.py
--------------------------
Sunday batch: gather the past 7 days of (pick, outcome) pairs, send to Claude,
get back a short Markdown memo identifying what's working / what isn't /
suggested rule changes.  Output: docs/data/weekly/<sunday-date>.md
"""
from __future__ import annotations
import argparse, csv, datetime as dt, glob, json, logging, re, sys, time
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from mlb_edge import claude_analyzer as ca

log = logging.getLogger(__name__)
ABBR_FIX = {"CHW": "CWS", "WSH": "WSH", "OAK": "ATH",
            "KCR": "KC", "TBR": "TB", "ARI": "AZ"}


def fetch_results(date):
    url = f"https://statsapi.mlb.com/api/v1/schedule?sportId=1&date={date}&hydrate=team"
    try:
        with urllib.request.urlopen(url, timeout=20) as r:
            j = json.load(r)
    except Exception:
        return {}
    out = {}
    for d in j.get("dates", []):
        for g in d.get("games", []):
            t = g["teams"]
            a = t["away"]["team"].get("abbreviation") or ""
            h = t["home"]["team"].get("abbreviation") or ""
            out[f"{a}@{h}"] = dict(
                away=a, home=h,
                away_score=t["away"].get("score"),
                home_score=t["home"].get("score"),
                status=g.get("status", {}).get("detailedState", ""),
            )
    return out


def lookup(results, away, home):
    for k in (f"{away}@{home}", f"{ABBR_FIX.get(away,away)}@{ABBR_FIX.get(home,home)}"):
        if k in results: return results[k]
    return None


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--end-date", help="ISO date (last day in window). Default: today UTC.")
    p.add_argument("--days", type=int, default=7)
    p.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args(argv)

    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(name)s: %(message)s")

    end = dt.date.fromisoformat(args.end_date) if args.end_date else dt.datetime.utcnow().date()
    dates = [(end - dt.timedelta(days=i)).isoformat() for i in range(args.days - 1, -1, -1)]
    log.info("weekly memo window: %s ... %s", dates[0], dates[-1])

    repo = args.repo_root
    pairs = []
    for date in dates:
        csv_path = repo / "docs" / "data" / f"picks_{date}_diag.csv"
        if not csv_path.exists():
            continue
        results = fetch_results(date)
        time.sleep(0.2)
        for row in csv.DictReader(csv_path.open()):
            m = re.match(r"\s*([A-Z]+)\s*@\s*([A-Z]+)", row.get("matchup", ""))
            if not m: continue
            away, home = m.group(1), m.group(2)
            res = lookup(results, away, home)
            if not res or res["status"] not in ("Final", "Game Over", "Completed Early"): continue
            if res["away_score"] is None: continue
            pick = (row.get("pick") or "").strip()
            pick_norm = ABBR_FIX.get(pick, pick)
            pick_is_home = pick_norm == res["home"] or pick == res["home"]
            home_won = res["home_score"] > res["away_score"]
            pick_won = (pick_is_home and home_won) or (not pick_is_home and not home_won)
            pairs.append({
                "date": date,
                "matchup": row["matchup"],
                "pick": pick,
                "model_prob": row.get("full_prob"),
                "fair_prob": row.get("fair_prob"),
                "edge_pp": row.get("edge_pp"),
                "tier": row.get("tier"),
                "signals": row.get("signals"),
                "actual_score": f"{res['away_score']}-{res['home_score']}",
                "won": pick_won,
            })

    if not pairs:
        log.warning("no graded pairs in window — bailing")
        return 0
    log.info("collected %d graded pairs across %d days", len(pairs), len(dates))

    if args.dry_run:
        print(json.dumps(pairs[:3], indent=2))
        log.info("dry run — not calling Claude")
        return 0

    r = ca.weekly_memo(pairs)
    if not r.ok:
        log.error("Claude call failed: %s", r.error)
        return 1

    out_dir = repo / "docs" / "data" / "weekly"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{end.isoformat()}.md"
    header = (f"# Weekly memo — week ending {end.isoformat()}\n\n"
              f"_Window: {dates[0]} to {dates[-1]} · {len(pairs)} graded picks · "
              f"{sum(1 for p in pairs if p['won'])} wins ({sum(1 for p in pairs if p['won'])/len(pairs):.1%})_\n\n"
              f"_Generated by `{r.model}` · {r.input_tokens} in / {r.output_tokens} out tokens_\n\n---\n\n")
    out_path.write_text(header + r.text + "\n")
    log.info("wrote %s", out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
